baseURL: https://glittering-kataifi-d0efb3.netlify.app/
languageCode: en-us
title: Blog stuff
theme: PaperMod

languages:
  en:
    params:
      linkedin: https://linkedin.com/whoever
    title: My blog
    weight: 1
  vn:
    params:
      navigation:
        help: Aide
    title: Sieu nhan
    weight: 2

params:
  custom_css: ["css/extended/custom.css"]
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  comments: true
  homeInfoParams:
    Title: "Hello there"
    Content: "Welcome to my blog. Here you find will some cool stuffs."

  socialIcons:
    - name: github
      url: "https://github.com"
    - name: twitter
      url: "https://twitter.com"
    - name: facebook
      url: "https://facebook.com"

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 5
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
