---
baseURL: https://blogt.xyz/
defaultContentLanguage: vn
languagCode: en-us
title: Podcast - Khong Ten
theme: PaperMod
languages:
  vn:
    contentDir: content/vn
    languageName: Vietnamese
    languageCode: vi
    params:
      navigation:
        help: Aide
    title: Blog
    weight: 2
    homeInfoParams:
      Title: Xin chào
      Content: Yoyo
    menu:
      main:
      - identifier: Phân loại
        name: Phân loại
        url: "/categories/"
        weight: 10
      - identifier: Tags
        name: Tags
        url: "/tags/"
        weight: 20
      - identifier: Tổng hợp
        name: Tổng hợp
        url: "/archives/"
        weight: 30
      - identifier: Tìm kiếm
        name: Tìm kiếm
        url: "/search"
        weight: 5
params:
  custom_css:
  - css/extended/custom.css
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
    - title
    - permalink
    - summary
    - content
  comments: true
  homeInfoParams:
    Title: Hello there
    Content: Welcome to my blog. Here you find will some cool stuffs.
  socialIcons:
  - name: github
    url: https://github.com
  - name: twitter
    url: https://twitter.com
  - name: facebook
    url: https://facebook.com
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
